### ISSUE TITLE
Web UI code style

### ISSUE THREAD

**Issue by edvinerikson** [EmulatorNexus/Advanced-Chat#1]
Hi!
Before i start complaining.. I just want to say that this is really cool, when i saw that the UI is being built with React i got like **"WOW! This is awesome!"** :smile: 

But.. As a JavaScript developer i get really annoyed looking at the code e.g methods is written like this:
```javascript
//Wrong
function Foo()
{
  console.log('Bar');
}

//Correct
function Foo() {
  console.log('Bar');
}
```
Variables isn't [lowerCamelCase](https://github.com/felixge/node-style-guide#use-lowercamelcase-for-variables-properties-and-function-names):
```javascript
var s_Message = "Msg"; // Wrong
var sMessage = "Msg"; // Correct
```

I would suggest that the UI should follow the [node-style-guide](https://github.com/felixge/node-style-guide) and I'm willing to help you achieve that! :smiley: 

Kind Regards,
Edvin

**Comment by OrfeasZ** [comment]
The code convention used in this project is based off-of personal preference and experience, and for consistency across multiple personal projects in multiple languages.
This mod is not meant to dictate coding guidelines for any other WebUI packages, and should in no way be considered as a definitive example.

Additionally, the usage of React is not a requirement, but a personal choice because of the performance benefits it provides.
